<Project Sdk="Microsoft.NET.Sdk"><ItemGroup><ProjectReference Include="../DecisionSharp.Core/DecisionSharp.Core.csproj"/><ProjectReference Include="../DecisionSharp.Jev/DecisionSharp.Jev.csproj"/><PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="10.10.0"/><PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.7"/></ItemGroup></Project>